In [2]:
#EXPT -02  ---- NumPy - Array and matrices
#Numpy inner product
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("a=",a)
print("b=",b)
print("inner product",np.inner(a,b))

a= [1 2 3]
b= [4 5 6]
inner product 32


In [8]:
#matrix transpose
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print("a",np.transpose(a))
print("a=",a.T)

a [[1 3 5]
 [2 4 6]]
a= [[1 3 5]
 [2 4 6]]


In [11]:
#matrix determinant
a=np.array([[1,2,2],
           [2,2,1],
           [1,3,1]])
det=np.linalg.det(a)
print("\nDeterminant",np.round(det))


Determinant 5.0


In [13]:
#true inverse of matrix
a=np.array([[1,2,2],
           [2,2,1],
           [1,3,1]])
inv=np.linalg.inv(a)
print("\nInverse",inv)



Inverse [[-0.2  0.8 -0.4]
 [-0.2 -0.2  0.6]
 [ 0.8 -0.2 -0.4]]


In [15]:
#eigen values and eigen vectors
a=np.array([[2,2,1],
           [1,3,1],
           [1,2,2]])
w,v=np.linalg.eig(a)
print("Eigen values",w)
print("Eigen vectors",v)

Eigen values [1. 5. 1.]
Eigen vectors [[-0.90453403  0.57735027  0.14313116]
 [ 0.30151134  0.57735027 -0.49893474]
 [ 0.30151134  0.57735027  0.85473832]]


In [17]:
#Rank 
a=np.arange(1,10)
a.shape=(3,3)
rank=np.linalg.matrix_rank(a)
print("\n rank",rank)


 rank 2


In [21]:
#numpy dot product
c=np.matrix([[1,2],[3,4]])
d=np.matrix([[5,6,7],[8,9,10]])
print(np.dot(c,d))

[[21 24 27]
 [47 54 61]]
